# 激活test配置
spring:
  profiles:
    active: "test"

---

spring:
  config:
    activate:
      on-profile: "dev"

name: dev.sisyphuswxg.com

---

spring:
  config:
    activate:
      on-profile: "test"

name: test.sisyphuswxg.com

---

spring:
  config:
    activate:
      on-profile: "prod"

name: prod.sisyphuswxg.com